set(rme_H
${CMAKE_CURRENT_LIST_DIR}/about_window.h
${CMAKE_CURRENT_LIST_DIR}/action.h
${CMAKE_CURRENT_LIST_DIR}/application.h
${CMAKE_CURRENT_LIST_DIR}/artprovider.h
${CMAKE_CURRENT_LIST_DIR}/autoborder_preview.h
${CMAKE_CURRENT_LIST_DIR}/basemap.h
${CMAKE_CURRENT_LIST_DIR}/bitmap_font.h
${CMAKE_CURRENT_LIST_DIR}/border_learning.h
${CMAKE_CURRENT_LIST_DIR}/border_learning_window.h
${CMAKE_CURRENT_LIST_DIR}/border_workspace_window.h
${CMAKE_CURRENT_LIST_DIR}/browse_tile_window.h
${CMAKE_CURRENT_LIST_DIR}/brush.h
${CMAKE_CURRENT_LIST_DIR}/brush_enums.h
${CMAKE_CURRENT_LIST_DIR}/carpet_brush.h
${CMAKE_CURRENT_LIST_DIR}/client_assets.h
${CMAKE_CURRENT_LIST_DIR}/client_assets_manifest.h
${CMAKE_CURRENT_LIST_DIR}/client_version.h
${CMAKE_CURRENT_LIST_DIR}/common.h
${CMAKE_CURRENT_LIST_DIR}/common_windows.h
${CMAKE_CURRENT_LIST_DIR}/complexitem.h
${CMAKE_CURRENT_LIST_DIR}/con_vector.h
${CMAKE_CURRENT_LIST_DIR}/container_properties_window.h
${CMAKE_CURRENT_LIST_DIR}/copybuffer.h
${CMAKE_CURRENT_LIST_DIR}/cross_client_clipboard.h
${CMAKE_CURRENT_LIST_DIR}/cross_client_paste_dialog.h
${CMAKE_CURRENT_LIST_DIR}/creature.h
${CMAKE_CURRENT_LIST_DIR}/creature_brush.h
${CMAKE_CURRENT_LIST_DIR}/creatures.h
${CMAKE_CURRENT_LIST_DIR}/dat_debug_view.h
${CMAKE_CURRENT_LIST_DIR}/dcbutton.h
${CMAKE_CURRENT_LIST_DIR}/depot_conversion_validation.h
${CMAKE_CURRENT_LIST_DIR}/definitions.h
${CMAKE_CURRENT_LIST_DIR}/doodad_brush.h
${CMAKE_CURRENT_LIST_DIR}/editor.h
${CMAKE_CURRENT_LIST_DIR}/editor_disposal.h
${CMAKE_CURRENT_LIST_DIR}/editor_tabs.h
${CMAKE_CURRENT_LIST_DIR}/extension.h
${CMAKE_CURRENT_LIST_DIR}/extension_window.h
${CMAKE_CURRENT_LIST_DIR}/find_item_window.h
${CMAKE_CURRENT_LIST_DIR}/file_transaction.h
${CMAKE_CURRENT_LIST_DIR}/favorites_manager.h
${CMAKE_CURRENT_LIST_DIR}/favorites_resources.h
${CMAKE_CURRENT_LIST_DIR}/palette_favorites.h
${CMAKE_CURRENT_LIST_DIR}/filehandle.h
${CMAKE_CURRENT_LIST_DIR}/gl_renderer.h
${CMAKE_CURRENT_LIST_DIR}/post_process_renderer.h
${CMAKE_CURRENT_LIST_DIR}/graphics.h
${CMAKE_CURRENT_LIST_DIR}/ground_brush.h
${CMAKE_CURRENT_LIST_DIR}/gui.h
${CMAKE_CURRENT_LIST_DIR}/gui_ids.h
${CMAKE_CURRENT_LIST_DIR}/hotkey_dialog.h
${CMAKE_CURRENT_LIST_DIR}/hotkey_manager.h
${CMAKE_CURRENT_LIST_DIR}/quick_command_palette.h
${CMAKE_CURRENT_LIST_DIR}/house.h
${CMAKE_CURRENT_LIST_DIR}/house_brush.h
${CMAKE_CURRENT_LIST_DIR}/house_exit_brush.h
${CMAKE_CURRENT_LIST_DIR}/house_paste_transaction.h
${CMAKE_CURRENT_LIST_DIR}/ingame_preview/ingame_preview_window.h
${CMAKE_CURRENT_LIST_DIR}/ingame_preview/playtest_controller.h
${CMAKE_CURRENT_LIST_DIR}/ingame_preview/playtest_input.h
${CMAKE_CURRENT_LIST_DIR}/ingame_preview/playtest_map.h
${CMAKE_CURRENT_LIST_DIR}/ingame_preview/playtest_weather.h
${CMAKE_CURRENT_LIST_DIR}/ingame_preview/playtest_hud.h
${CMAKE_CURRENT_LIST_DIR}/iomap.h
${CMAKE_CURRENT_LIST_DIR}/iomap_otbm.h
${CMAKE_CURRENT_LIST_DIR}/iominimap.h
${CMAKE_CURRENT_LIST_DIR}/minimap_import.h
${CMAKE_CURRENT_LIST_DIR}/minimap_import_window.h
${CMAKE_CURRENT_LIST_DIR}/minimap_format.h
${CMAKE_CURRENT_LIST_DIR}/png_map_import.h
${CMAKE_CURRENT_LIST_DIR}/png_map_import_window.h
${CMAKE_CURRENT_LIST_DIR}/item.h
${CMAKE_CURRENT_LIST_DIR}/item_id_codec.h
${CMAKE_CURRENT_LIST_DIR}/item_id_mapping.h
${CMAKE_CURRENT_LIST_DIR}/item_attributes.h
${CMAKE_CURRENT_LIST_DIR}/items.h
${CMAKE_CURRENT_LIST_DIR}/light_drawer.h
${CMAKE_CURRENT_LIST_DIR}/main.h
${CMAKE_CURRENT_LIST_DIR}/main_menubar.h
${CMAKE_CURRENT_LIST_DIR}/main_toolbar.h
${CMAKE_CURRENT_LIST_DIR}/map.h
${CMAKE_CURRENT_LIST_DIR}/map_diagnostics.h
${CMAKE_CURRENT_LIST_DIR}/map_diagnostics_scanner.h
${CMAKE_CURRENT_LIST_DIR}/map_diagnostics_window.h
${CMAKE_CURRENT_LIST_DIR}/map_format.h
${CMAKE_CURRENT_LIST_DIR}/map_item_id_converter.h
${CMAKE_CURRENT_LIST_DIR}/map_item_id_converter_window.h
${CMAKE_CURRENT_LIST_DIR}/map_allocator.h
${CMAKE_CURRENT_LIST_DIR}/map_display.h
${CMAKE_CURRENT_LIST_DIR}/map_drawer.h
${CMAKE_CURRENT_LIST_DIR}/map_overlay_text.h
${CMAKE_CURRENT_LIST_DIR}/map_region.h
${CMAKE_CURRENT_LIST_DIR}/map_chunk_revision.h
${CMAKE_CURRENT_LIST_DIR}/map_chunk_geometry_cache.h
${CMAKE_CURRENT_LIST_DIR}/map_chunk_render_cache.h
${CMAKE_CURRENT_LIST_DIR}/atlas_page_epochs.h
${CMAKE_CURRENT_LIST_DIR}/map_tab.h
${CMAKE_CURRENT_LIST_DIR}/map_window.h
${CMAKE_CURRENT_LIST_DIR}/materials_workbench_window.h
${CMAKE_CURRENT_LIST_DIR}/materials.h
${CMAKE_CURRENT_LIST_DIR}/minimap_window.h
${CMAKE_CURRENT_LIST_DIR}/mount_id_resolver.h
${CMAKE_CURRENT_LIST_DIR}/monster_definition.h
${CMAKE_CURRENT_LIST_DIR}/monster_definition_creation.h
${CMAKE_CURRENT_LIST_DIR}/monster_section_codec.h
${CMAKE_CURRENT_LIST_DIR}/monster_editor_dialog.h
${CMAKE_CURRENT_LIST_DIR}/monster_spell_area.h
${CMAKE_CURRENT_LIST_DIR}/monster_spell_preview.h
${CMAKE_CURRENT_LIST_DIR}/npc_definition.h
${CMAKE_CURRENT_LIST_DIR}/npc_definition_creation.h
${CMAKE_CURRENT_LIST_DIR}/npc_editor_dialog.h
${CMAKE_CURRENT_LIST_DIR}/outfit_color_picker.h
${CMAKE_CURRENT_LIST_DIR}/spell_definition.h
${CMAKE_CURRENT_LIST_DIR}/spell_area_library.h
${CMAKE_CURRENT_LIST_DIR}/spell_area_editor_dialog.h
${CMAKE_CURRENT_LIST_DIR}/spell_area_resolver.h
${CMAKE_CURRENT_LIST_DIR}/spell_editor_dialog.h
${CMAKE_CURRENT_LIST_DIR}/spell_visual_browser_dialog.h
${CMAKE_CURRENT_LIST_DIR}/minimap_canvas.h
${CMAKE_CURRENT_LIST_DIR}/minimap_style.h
${CMAKE_CURRENT_LIST_DIR}/minimap_page_cache.h
${CMAKE_CURRENT_LIST_DIR}/mt_rand.h
${CMAKE_CURRENT_LIST_DIR}/numbertextctrl.h
${CMAKE_CURRENT_LIST_DIR}/object_pool.h
${CMAKE_CURRENT_LIST_DIR}/old_properties_window.h
${CMAKE_CURRENT_LIST_DIR}/otml.h
${CMAKE_CURRENT_LIST_DIR}/outfit.h
${CMAKE_CURRENT_LIST_DIR}/palette_brushlist.h
${CMAKE_CURRENT_LIST_DIR}/palette_brush_tool.h
${CMAKE_CURRENT_LIST_DIR}/palette_common.h
${CMAKE_CURRENT_LIST_DIR}/palette_creature.h
${CMAKE_CURRENT_LIST_DIR}/palette_house.h
${CMAKE_CURRENT_LIST_DIR}/palette_waypoints.h
${CMAKE_CURRENT_LIST_DIR}/palette_window.h
${CMAKE_CURRENT_LIST_DIR}/pngfiles.h
${CMAKE_CURRENT_LIST_DIR}/position.h
${CMAKE_CURRENT_LIST_DIR}/positionctrl.h
	${CMAKE_CURRENT_LIST_DIR}/procedural_map_generator.h
	${CMAKE_CURRENT_LIST_DIR}/procedural_map_generator_window.h
${CMAKE_CURRENT_LIST_DIR}/preferences.h
${CMAKE_CURRENT_LIST_DIR}/process_com.h
${CMAKE_CURRENT_LIST_DIR}/properties_window.h
${CMAKE_CURRENT_LIST_DIR}/raw_brush.h
${CMAKE_CURRENT_LIST_DIR}/replace_items_window.h
${CMAKE_CURRENT_LIST_DIR}/replace_tool/advanced_replace_window.h
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_engine.h
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_execution_plan.h
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_item_grid_panel.h
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_library_catalog.h
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_library_panel.h
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_rule.h
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_rule_builder_panel.h
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_rule_editor.h
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_rule_manager.h
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_scope.h
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_visual_similarity_service.h
${CMAKE_CURRENT_LIST_DIR}/replace_tool/visual_similarity_index.h
${CMAKE_CURRENT_LIST_DIR}/result_window.h
${CMAKE_CURRENT_LIST_DIR}/rme_forward_declarations.h
${CMAKE_CURRENT_LIST_DIR}/selection.h
${CMAKE_CURRENT_LIST_DIR}/session_id.h
${CMAKE_CURRENT_LIST_DIR}/settings.h
${CMAKE_CURRENT_LIST_DIR}/server_content_index.h
${CMAKE_CURRENT_LIST_DIR}/source_text_utils.h
${CMAKE_CURRENT_LIST_DIR}/lua_source_scanner.h
${CMAKE_CURRENT_LIST_DIR}/server_content_browser_dialog.h
${CMAKE_CURRENT_LIST_DIR}/server_item_id_map.h
${CMAKE_CURRENT_LIST_DIR}/server_vocation_catalog.h
${CMAKE_CURRENT_LIST_DIR}/server_visual_catalog.h
${CMAKE_CURRENT_LIST_DIR}/editor_autosave_state.h
${CMAKE_CURRENT_LIST_DIR}/editor_source_monitor.h
${CMAKE_CURRENT_LIST_DIR}/source_compare_dialog.h
${CMAKE_CURRENT_LIST_DIR}/server_workspace.h
${CMAKE_CURRENT_LIST_DIR}/theme.h
${CMAKE_CURRENT_LIST_DIR}/spawn.h
${CMAKE_CURRENT_LIST_DIR}/spawn_format.h
${CMAKE_CURRENT_LIST_DIR}/spawn_export_window.h
${CMAKE_CURRENT_LIST_DIR}/spawn_converter_window.h
${CMAKE_CURRENT_LIST_DIR}/spawn_xml_converter.h
${CMAKE_CURRENT_LIST_DIR}/spawn_brush.h
${CMAKE_CURRENT_LIST_DIR}/sprites.h
${CMAKE_CURRENT_LIST_DIR}/sprite_appearances.h
${CMAKE_CURRENT_LIST_DIR}/sprite_preloader.h
${CMAKE_CURRENT_LIST_DIR}/table_brush.h
${CMAKE_CURRENT_LIST_DIR}/templates.h
${CMAKE_CURRENT_LIST_DIR}/threads.h
${CMAKE_CURRENT_LIST_DIR}/tile.h
${CMAKE_CURRENT_LIST_DIR}/tileset.h
${CMAKE_CURRENT_LIST_DIR}/town.h
${CMAKE_CURRENT_LIST_DIR}/wall_brush.h
${CMAKE_CURRENT_LIST_DIR}/waypoint_brush.h
${CMAKE_CURRENT_LIST_DIR}/waypoints.h
${CMAKE_CURRENT_LIST_DIR}/welcome_dialog.h
${CMAKE_CURRENT_LIST_DIR}/workspace_session.h
${CMAKE_CURRENT_LIST_DIR}/version_info.h
${CMAKE_CURRENT_LIST_DIR}/zones.h
${CMAKE_CURRENT_LIST_DIR}/zone_brush.h
${CMAKE_CURRENT_LIST_DIR}/palette_zones.h
${CMAKE_CURRENT_LIST_DIR}/palette_saved_terrain.h
${CMAKE_CURRENT_LIST_DIR}/terrain_stamp/terrain_stamp.h
${CMAKE_CURRENT_LIST_DIR}/terrain_stamp/terrain_stamp_library.h
${CMAKE_CURRENT_LIST_DIR}/tileset_window.h
${CMAKE_CURRENT_LIST_DIR}/add_tileset_window.h
${CMAKE_CURRENT_LIST_DIR}/add_item_window.h
)

set(rme_SRC
${CMAKE_CURRENT_LIST_DIR}/about_window.cpp
${CMAKE_CURRENT_LIST_DIR}/action.cpp
${CMAKE_CURRENT_LIST_DIR}/application.cpp
${CMAKE_CURRENT_LIST_DIR}/artprovider.cpp
${CMAKE_CURRENT_LIST_DIR}/autoborder_preview.cpp
${CMAKE_CURRENT_LIST_DIR}/basemap.cpp
${CMAKE_CURRENT_LIST_DIR}/bitmap_font.cpp
${CMAKE_CURRENT_LIST_DIR}/border_learning.cpp
${CMAKE_CURRENT_LIST_DIR}/border_learning_map.cpp
${CMAKE_CURRENT_LIST_DIR}/border_learning_window.cpp
${CMAKE_CURRENT_LIST_DIR}/border_workspace_window.cpp
${CMAKE_CURRENT_LIST_DIR}/brush.cpp
${CMAKE_CURRENT_LIST_DIR}/brush_tables.cpp
${CMAKE_CURRENT_LIST_DIR}/browse_tile_window.cpp
${CMAKE_CURRENT_LIST_DIR}/positionctrl.cpp
	${CMAKE_CURRENT_LIST_DIR}/procedural_map_generator.cpp
	${CMAKE_CURRENT_LIST_DIR}/procedural_map_generator_window.cpp
${CMAKE_CURRENT_LIST_DIR}/carpet_brush.cpp
${CMAKE_CURRENT_LIST_DIR}/client_assets.cpp
${CMAKE_CURRENT_LIST_DIR}/client_assets_manifest.cpp
${CMAKE_CURRENT_LIST_DIR}/client_version.cpp
${CMAKE_CURRENT_LIST_DIR}/common.cpp
${CMAKE_CURRENT_LIST_DIR}/common_windows.cpp
${CMAKE_CURRENT_LIST_DIR}/complexitem.cpp
${CMAKE_CURRENT_LIST_DIR}/container_properties_window.cpp
${CMAKE_CURRENT_LIST_DIR}/copybuffer.cpp
${CMAKE_CURRENT_LIST_DIR}/cross_client_clipboard.cpp
${CMAKE_CURRENT_LIST_DIR}/cross_client_paste_dialog.cpp
${CMAKE_CURRENT_LIST_DIR}/creature_brush.cpp
${CMAKE_CURRENT_LIST_DIR}/creature.cpp
${CMAKE_CURRENT_LIST_DIR}/creatures.cpp
${CMAKE_CURRENT_LIST_DIR}/dat_debug_view.cpp
${CMAKE_CURRENT_LIST_DIR}/dcbutton.cpp
${CMAKE_CURRENT_LIST_DIR}/depot_conversion_validation.cpp
${CMAKE_CURRENT_LIST_DIR}/doodad_brush.cpp
${CMAKE_CURRENT_LIST_DIR}/editor.cpp
${CMAKE_CURRENT_LIST_DIR}/editor_resource_session.cpp
${CMAKE_CURRENT_LIST_DIR}/editor_tabs.cpp
${CMAKE_CURRENT_LIST_DIR}/eraser_brush.cpp
${CMAKE_CURRENT_LIST_DIR}/extension.cpp
${CMAKE_CURRENT_LIST_DIR}/extension_window.cpp
${CMAKE_CURRENT_LIST_DIR}/find_item_window.cpp
${CMAKE_CURRENT_LIST_DIR}/filehandle.cpp
${CMAKE_CURRENT_LIST_DIR}/graphics.cpp
${CMAKE_CURRENT_LIST_DIR}/gl_renderer.cpp
${CMAKE_CURRENT_LIST_DIR}/map_chunk_render_cache.cpp
${CMAKE_CURRENT_LIST_DIR}/post_process_renderer.cpp
${CMAKE_CURRENT_LIST_DIR}/ground_brush.cpp
${CMAKE_CURRENT_LIST_DIR}/gui.cpp
${CMAKE_CURRENT_LIST_DIR}/hotkey_dialog.cpp
${CMAKE_CURRENT_LIST_DIR}/hotkey_manager.cpp
${CMAKE_CURRENT_LIST_DIR}/favorites_manager.cpp
${CMAKE_CURRENT_LIST_DIR}/favorites_resources.cpp
${CMAKE_CURRENT_LIST_DIR}/palette_favorites.cpp
${CMAKE_CURRENT_LIST_DIR}/quick_command_palette.cpp
${CMAKE_CURRENT_LIST_DIR}/house_brush.cpp
${CMAKE_CURRENT_LIST_DIR}/house.cpp
${CMAKE_CURRENT_LIST_DIR}/house_exit_brush.cpp
${CMAKE_CURRENT_LIST_DIR}/ingame_preview/ingame_preview_window.cpp
${CMAKE_CURRENT_LIST_DIR}/ingame_preview/playtest_controller.cpp
${CMAKE_CURRENT_LIST_DIR}/ingame_preview/playtest_map.cpp
${CMAKE_CURRENT_LIST_DIR}/ingame_preview/playtest_weather.cpp
${CMAKE_CURRENT_LIST_DIR}/ingame_preview/playtest_hud.cpp
${CMAKE_CURRENT_LIST_DIR}/iomap.cpp
${CMAKE_CURRENT_LIST_DIR}/iomap_otbm.cpp
${CMAKE_CURRENT_LIST_DIR}/iominimap.cpp
${CMAKE_CURRENT_LIST_DIR}/minimap_import.cpp
${CMAKE_CURRENT_LIST_DIR}/minimap_import_window.cpp
${CMAKE_CURRENT_LIST_DIR}/png_map_import.cpp
${CMAKE_CURRENT_LIST_DIR}/png_map_import_window.cpp
${CMAKE_CURRENT_LIST_DIR}/item_attributes.cpp
${CMAKE_CURRENT_LIST_DIR}/item.cpp
${CMAKE_CURRENT_LIST_DIR}/item_id_codec.cpp
${CMAKE_CURRENT_LIST_DIR}/item_id_mapping.cpp
${CMAKE_CURRENT_LIST_DIR}/items.cpp
${CMAKE_CURRENT_LIST_DIR}/light_drawer.cpp
${CMAKE_CURRENT_LIST_DIR}/main_menubar.cpp
${CMAKE_CURRENT_LIST_DIR}/main_toolbar.cpp
${CMAKE_CURRENT_LIST_DIR}/map.cpp
${CMAKE_CURRENT_LIST_DIR}/map_diagnostics.cpp
${CMAKE_CURRENT_LIST_DIR}/map_diagnostics_scanner.cpp
${CMAKE_CURRENT_LIST_DIR}/map_diagnostics_window.cpp
${CMAKE_CURRENT_LIST_DIR}/map_format.cpp
${CMAKE_CURRENT_LIST_DIR}/map_item_id_converter.cpp
${CMAKE_CURRENT_LIST_DIR}/map_item_id_converter_window.cpp
${CMAKE_CURRENT_LIST_DIR}/map_display.cpp
${CMAKE_CURRENT_LIST_DIR}/map_drawer.cpp
${CMAKE_CURRENT_LIST_DIR}/map_region.cpp
${CMAKE_CURRENT_LIST_DIR}/map_tab.cpp
${CMAKE_CURRENT_LIST_DIR}/map_window.cpp
${CMAKE_CURRENT_LIST_DIR}/materials_workbench_window.cpp
${CMAKE_CURRENT_LIST_DIR}/materials.cpp
${CMAKE_CURRENT_LIST_DIR}/minimap_window.cpp
${CMAKE_CURRENT_LIST_DIR}/mount_id_resolver.cpp
${CMAKE_CURRENT_LIST_DIR}/monster_definition.cpp
${CMAKE_CURRENT_LIST_DIR}/monster_definition_creation.cpp
${CMAKE_CURRENT_LIST_DIR}/monster_section_codec.cpp
${CMAKE_CURRENT_LIST_DIR}/monster_editor_dialog.cpp
${CMAKE_CURRENT_LIST_DIR}/monster_editor_sections.cpp
${CMAKE_CURRENT_LIST_DIR}/monster_editor_attacks.cpp
${CMAKE_CURRENT_LIST_DIR}/monster_spell_area.cpp
${CMAKE_CURRENT_LIST_DIR}/monster_spell_preview.cpp
${CMAKE_CURRENT_LIST_DIR}/npc_definition.cpp
${CMAKE_CURRENT_LIST_DIR}/npc_definition_creation.cpp
${CMAKE_CURRENT_LIST_DIR}/npc_editor_dialog.cpp
${CMAKE_CURRENT_LIST_DIR}/outfit_color_picker.cpp
${CMAKE_CURRENT_LIST_DIR}/spell_definition.cpp
${CMAKE_CURRENT_LIST_DIR}/spell_area_library.cpp
${CMAKE_CURRENT_LIST_DIR}/spell_area_editor_dialog.cpp
${CMAKE_CURRENT_LIST_DIR}/spell_area_resolver.cpp
${CMAKE_CURRENT_LIST_DIR}/spell_editor_dialog.cpp
${CMAKE_CURRENT_LIST_DIR}/spell_visual_browser_dialog.cpp
${CMAKE_CURRENT_LIST_DIR}/minimap_canvas.cpp
${CMAKE_CURRENT_LIST_DIR}/minimap_style.cpp
${CMAKE_CURRENT_LIST_DIR}/minimap_page_cache.cpp
${CMAKE_CURRENT_LIST_DIR}/mkpch.cpp
${CMAKE_CURRENT_LIST_DIR}/mt_rand.cpp
${CMAKE_CURRENT_LIST_DIR}/new_map_tab_dialog.cpp
${CMAKE_CURRENT_LIST_DIR}/numbertextctrl.cpp
${CMAKE_CURRENT_LIST_DIR}/object_pool.cpp
${CMAKE_CURRENT_LIST_DIR}/old_properties_window.cpp
${CMAKE_CURRENT_LIST_DIR}/palette_brushlist.cpp
${CMAKE_CURRENT_LIST_DIR}/palette_brush_tool.cpp
${CMAKE_CURRENT_LIST_DIR}/palette_common.cpp
${CMAKE_CURRENT_LIST_DIR}/palette_creature.cpp
${CMAKE_CURRENT_LIST_DIR}/palette_house.cpp
${CMAKE_CURRENT_LIST_DIR}/palette_waypoints.cpp
${CMAKE_CURRENT_LIST_DIR}/palette_window.cpp
${CMAKE_CURRENT_LIST_DIR}/pngfiles.cpp
${CMAKE_CURRENT_LIST_DIR}/preferences.cpp
${CMAKE_CURRENT_LIST_DIR}/process_com.cpp
${CMAKE_CURRENT_LIST_DIR}/properties_window.cpp
${CMAKE_CURRENT_LIST_DIR}/raw_brush.cpp
${CMAKE_CURRENT_LIST_DIR}/replace_items_window.cpp
${CMAKE_CURRENT_LIST_DIR}/replace_tool/advanced_replace_window.cpp
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_engine.cpp
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_execution_plan.cpp
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_item_grid_panel.cpp
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_library_catalog.cpp
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_library_panel.cpp
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_rule.cpp
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_rule_builder_panel.cpp
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_rule_editor.cpp
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_rule_manager.cpp
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_scope.cpp
${CMAKE_CURRENT_LIST_DIR}/replace_tool/replace_visual_similarity_service.cpp
${CMAKE_CURRENT_LIST_DIR}/replace_tool/visual_similarity_index.cpp
${CMAKE_CURRENT_LIST_DIR}/result_window.cpp
${CMAKE_CURRENT_LIST_DIR}/selection.cpp
${CMAKE_CURRENT_LIST_DIR}/session_id.cpp
${CMAKE_CURRENT_LIST_DIR}/settings.cpp
${CMAKE_CURRENT_LIST_DIR}/server_content_index.cpp
${CMAKE_CURRENT_LIST_DIR}/server_content_browser_dialog.cpp
${CMAKE_CURRENT_LIST_DIR}/server_item_id_map.cpp
${CMAKE_CURRENT_LIST_DIR}/server_vocation_catalog.cpp
${CMAKE_CURRENT_LIST_DIR}/server_visual_catalog.cpp
${CMAKE_CURRENT_LIST_DIR}/source_compare_dialog.cpp
${CMAKE_CURRENT_LIST_DIR}/server_workspace.cpp
${CMAKE_CURRENT_LIST_DIR}/theme.cpp
${CMAKE_CURRENT_LIST_DIR}/spawn_brush.cpp
${CMAKE_CURRENT_LIST_DIR}/spawn.cpp
${CMAKE_CURRENT_LIST_DIR}/spawn_format.cpp
${CMAKE_CURRENT_LIST_DIR}/spawn_format_map.cpp
${CMAKE_CURRENT_LIST_DIR}/spawn_export_window.cpp
${CMAKE_CURRENT_LIST_DIR}/spawn_converter_window.cpp
${CMAKE_CURRENT_LIST_DIR}/spawn_xml_converter.cpp
${CMAKE_CURRENT_LIST_DIR}/sprite_appearances.cpp
${CMAKE_CURRENT_LIST_DIR}/sprite_preloader.cpp
${CMAKE_CURRENT_LIST_DIR}/table_brush.cpp
${CMAKE_CURRENT_LIST_DIR}/templatemap76-74.cpp
${CMAKE_CURRENT_LIST_DIR}/templatemap81.cpp
${CMAKE_CURRENT_LIST_DIR}/templatemap854.cpp
${CMAKE_CURRENT_LIST_DIR}/tile.cpp
${CMAKE_CURRENT_LIST_DIR}/tileset.cpp
${CMAKE_CURRENT_LIST_DIR}/town.cpp
${CMAKE_CURRENT_LIST_DIR}/wall_brush.cpp
${CMAKE_CURRENT_LIST_DIR}/waypoint_brush.cpp
${CMAKE_CURRENT_LIST_DIR}/waypoints.cpp
${CMAKE_CURRENT_LIST_DIR}/welcome_dialog.cpp
${CMAKE_CURRENT_LIST_DIR}/workspace_session.cpp
${CMAKE_CURRENT_LIST_DIR}/zones.cpp
${CMAKE_CURRENT_LIST_DIR}/zone_brush.cpp
${CMAKE_CURRENT_LIST_DIR}/palette_zones.cpp
${CMAKE_CURRENT_LIST_DIR}/palette_saved_terrain.cpp
${CMAKE_CURRENT_LIST_DIR}/terrain_stamp/terrain_stamp.cpp
${CMAKE_CURRENT_LIST_DIR}/terrain_stamp/terrain_stamp_library.cpp
${CMAKE_CURRENT_LIST_DIR}/tileset_window.cpp
${CMAKE_CURRENT_LIST_DIR}/add_tileset_window.cpp
${CMAKE_CURRENT_LIST_DIR}/add_item_window.cpp
)

# ============================================================================
# Performance overlay — psapi (Windows RAM monitoring)
# Add the following line inside your target_link_libraries() call:
#
#   $<$<PLATFORM_ID:Windows>:psapi>
#
# Example:
#   target_link_libraries(${PROJECT_NAME}
#       ...existing libs...
#       $<$<PLATFORM_ID:Windows>:psapi>
#   )
# ============================================================================

# Multiplayer modules have independent wire/GUI boundaries.
list(APPEND rme_H
${CMAKE_CURRENT_LIST_DIR}/multiplayer_transport.h
${CMAKE_CURRENT_LIST_DIR}/multiplayer_protocol.h
${CMAKE_CURRENT_LIST_DIR}/multiplayer_crypto.h
${CMAKE_CURRENT_LIST_DIR}/multiplayer_codec.h
${CMAKE_CURRENT_LIST_DIR}/multiplayer_session.h
${CMAKE_CURRENT_LIST_DIR}/multiplayer_window.h
)
list(APPEND rme_SRC
${CMAKE_CURRENT_LIST_DIR}/multiplayer_transport.cpp
${CMAKE_CURRENT_LIST_DIR}/multiplayer_protocol.cpp
${CMAKE_CURRENT_LIST_DIR}/multiplayer_crypto.cpp
${CMAKE_CURRENT_LIST_DIR}/multiplayer_codec.cpp
${CMAKE_CURRENT_LIST_DIR}/multiplayer_session.cpp
${CMAKE_CURRENT_LIST_DIR}/multiplayer_window.cpp
)
set_source_files_properties(
	${CMAKE_CURRENT_LIST_DIR}/mount_id_resolver.cpp
	${CMAKE_CURRENT_LIST_DIR}/server_content_index.cpp
	${CMAKE_CURRENT_LIST_DIR}/server_content_browser_dialog.cpp
	${CMAKE_CURRENT_LIST_DIR}/server_item_id_map.cpp
	${CMAKE_CURRENT_LIST_DIR}/server_vocation_catalog.cpp
	${CMAKE_CURRENT_LIST_DIR}/server_visual_catalog.cpp
	${CMAKE_CURRENT_LIST_DIR}/monster_definition.cpp
	${CMAKE_CURRENT_LIST_DIR}/monster_definition_creation.cpp
	${CMAKE_CURRENT_LIST_DIR}/monster_section_codec.cpp
	${CMAKE_CURRENT_LIST_DIR}/monster_editor_dialog.cpp
	${CMAKE_CURRENT_LIST_DIR}/monster_editor_sections.cpp
	${CMAKE_CURRENT_LIST_DIR}/monster_editor_attacks.cpp
	${CMAKE_CURRENT_LIST_DIR}/monster_spell_area.cpp
	${CMAKE_CURRENT_LIST_DIR}/monster_spell_preview.cpp
	${CMAKE_CURRENT_LIST_DIR}/npc_definition.cpp
	${CMAKE_CURRENT_LIST_DIR}/npc_definition_creation.cpp
	${CMAKE_CURRENT_LIST_DIR}/npc_editor_dialog.cpp
	${CMAKE_CURRENT_LIST_DIR}/spell_definition.cpp
	${CMAKE_CURRENT_LIST_DIR}/spell_area_library.cpp
	${CMAKE_CURRENT_LIST_DIR}/spell_area_editor_dialog.cpp
	${CMAKE_CURRENT_LIST_DIR}/spell_area_resolver.cpp
	${CMAKE_CURRENT_LIST_DIR}/spell_editor_dialog.cpp
	${CMAKE_CURRENT_LIST_DIR}/spell_visual_browser_dialog.cpp
	${CMAKE_CURRENT_LIST_DIR}/multiplayer_transport.cpp
${CMAKE_CURRENT_LIST_DIR}/multiplayer_protocol.cpp
${CMAKE_CURRENT_LIST_DIR}/multiplayer_crypto.cpp
${CMAKE_CURRENT_LIST_DIR}/multiplayer_codec.cpp
${CMAKE_CURRENT_LIST_DIR}/multiplayer_session.cpp
${CMAKE_CURRENT_LIST_DIR}/multiplayer_window.cpp
PROPERTIES SKIP_UNITY_BUILD_INCLUSION ON)

# Keep local macros in the legacy RNG and standalone playtest modules isolated.
set_source_files_properties(
    ${CMAKE_CURRENT_LIST_DIR}/mt_rand.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ingame_preview/playtest_controller.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ingame_preview/playtest_map.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ingame_preview/playtest_weather.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ingame_preview/playtest_hud.cpp
    PROPERTIES SKIP_UNITY_BUILD_INCLUSION ON
)
